# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:


- master



pool:


  vmImage: 'ubuntu-latest'


strategy:


  matrix:


    Python27:


      python.version: '2.7'



steps:


- task: UsePythonVersion@0


  inputs:


    versionSpec: '$(python.version)'


  displayName: 'Use Python $(python.version)'


- script: python "a.py"



- task: PythonScript@0


  inputs:


    scriptSource: 'inline'


    script: |


      print('Hello world 1')


      print('Hello world 2')

      <repository>
  <id>demo2020</id>
  <url>https://pkgs.dev.azure.com/vinodghate/demo2020/_packaging/demo2020/maven/v1</url>
  <releases>
    <enabled>true</enabled>
  </releases>
  <snapshots>
    <enabled>true</enabled>
  </snapshots>
</repository>


<server>
      <id>demo2020</id>
      <username>vinodghate</username>
      <password>[PERSONAL_ACCESS_TOKEN]</password>
</server>

